all: ErrorModelSimpleEquant.dll CommonDiet.dll
	# Comment here preserves the prior tab
ErrorModelSimpleEquant.dll: ErrorModelSimpleEquant.cpp
	$(R_HOME)/bin/Rscript --vanilla -e "TMB::compile('ErrorModelSimpleEquant.cpp', '-O1 -g',DLLFLAGS='')"
CommonDiet.dll: CommonDiet.cpp
	$(R_HOME)/bin/Rscript --vanilla -e "TMB::compile('CommonDiet.cpp', '-O1 -g',DLLFLAGS='')"

clean:
	rm -rf *.dll
	rm -rf *o
